#!/bin/env bash

set -ex
printenv

echo CM_TAG = $CM_TAG

echo CM_BUILD_DIR = $CM_BUILD_DIR

echo CM_KEYSTORE = $CM_KEYSTORE
echo CM_KEYSTORE_PATH = $CM_KEYSTORE_PATH
echo CM_KEYSTORE_PASSWORD = $CM_KEYSTORE_PASSWORD
echo CM_KEY_ALIAS = $CM_KEY_ALIAS
echo CM_KEY_PASSWORD = $CM_KEY_PASSWORD

echo GITHUB_TOKEN = $GITHUB_TOKEN

echo FIREBASE_TOKEN = $FIREBASE_TOKEN
echo FIREBASE_ANDROID_APP_ID = $FIREBASE_ANDROID_APP_ID
echo FIREBASE_OPTIONS = $FIREBASE_OPTIONS
echo GOOGLE_SERVICES = $GOOGLE_SERVICES
