#!/bin/env bash

echo CM_TAG = $CM_TAG

echo CM_BUILD_DIR = $CM_BUILD_DIR

echo GITHUB_TOKEN = $GITHUB_TOKEN

echo FIREBASE_TOKEN = $FIREBASE_TOKEN
echo FIREBASE_ANDROID_APP_ID = $FIREBASE_ANDROID_APP_ID
